distribution_type: module
generated_by: Module::Install version 0.63
license: Perl
name: Data-SExpression
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0.25
  Class::Accessor::Fast: 0
  Parse::Yapp: 0
version: 0.3
